services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis-adebe:6666/0
      - CELERY_BROKER_URL=redis://redis-adebe:6666/0
      - CELERY_RESULT_BACKEND=redis://redis-adebe:6666/0
    depends_on:
      - redis-adebe
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: .
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis-adebe:6666/0
      - CELERY_BROKER_URL=redis://redis-adebe:6666/0
      - CELERY_RESULT_BACKEND=redis://redis-adebe:6666/0
    depends_on:
      - redis-adebe
    volumes:
      - .:/app
    command: celery -A app.core.celery_app.celery_app worker -l info

  redis-adebe:
    image: redis:7-alpine
    ports:
      - "6666:6379"

volumes:
  redis_data:
