services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis-adebe:6379/0
      - CELERY_RESULT_BACKEND=redis://redis-adebe:6379/0
    depends_on:
      - redis-adebe
    volumes:
      - .:/app
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: .
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis-adebe:6379/0
      - CELERY_RESULT_BACKEND=redis://redis-adebe:6379/0
    depends_on:
      - redis-adebe
    volumes:
      - .:/app
    command: uv run celery -A app.core.celery_app.celery_app worker -l info

  redis-adebe:
    image: redis:7-alpine
    volumes:
      - redis_data:/data

volumes:
  redis_data:
